swagger: '2.0'
info:
  version: '1.0.0'
  title: E-Food
schemes: [http]
host: e-food.com
basePath: /
consumes: [application/json]
produces: [application/json]
paths:
  /categories:
    get:
      tags: [menu]
      operationId: CategoryList
      responses:
        200:
          description: 'Get Category to show menu'
          schema:
            $ref: '#/definitions/Categories'
        400:
          description: Bad Request
        404:
          description: Categories Not Found

definitions:
  Categories:
    type: array
    items:
      type: object
      properties:
        BroadCategoryId:
          type: string
        Name:
          type: string
        ImageUrl:
          type: string
        IsActive:
          type: boolean
        SubCategories:
          type: array
          items:
            type: object
            properties:
              SubCategoryId:
                type: string
              Name:
                type: string
              ImageUrl:
                type: string
              IsActive:
                type: boolean
