// Code generated by go-swagger; DO NOT EDIT.

// Package restapi E-Food
//
//  Schemes:
//    http
//  Host: e-food.com
//  BasePath: /v1
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
