// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Minimal Pet Store Example
//
//  Schemes:
//    http
//  Host: example.org
//  BasePath: /api
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
