// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "E-Food",
    "version": "1.0.0"
  },
  "host": "e-food.com",
  "basePath": "/api",
  "paths": {
    "/get_categories": {
      "get": {
        "tags": [
          "menu"
        ],
        "operationId": "CategoryList",
        "parameters": [
          {
            "type": "string",
            "name": "kind",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Get Category to show menu",
            "schema": {
              "$ref": "#/definitions/Categories"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "404": {
            "description": "Categories Not Found"
          }
        }
      }
    }
  },
  "definitions": {
    "Categories": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "BroadCategoryId": {
            "type": "string"
          },
          "ImageUrl": {
            "type": "string"
          },
          "IsActive": {
            "type": "boolean"
          },
          "Name": {
            "type": "string"
          },
          "SubCategories": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "ImageUrl": {
                  "type": "string"
                },
                "IsActive": {
                  "type": "boolean"
                },
                "Name": {
                  "type": "string"
                },
                "SubCategoryId": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "E-Food",
    "version": "1.0.0"
  },
  "host": "e-food.com",
  "basePath": "/api",
  "paths": {
    "/get_categories": {
      "get": {
        "tags": [
          "menu"
        ],
        "operationId": "CategoryList",
        "parameters": [
          {
            "type": "string",
            "name": "kind",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Get Category to show menu",
            "schema": {
              "$ref": "#/definitions/Categories"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "404": {
            "description": "Categories Not Found"
          }
        }
      }
    }
  },
  "definitions": {
    "Categories": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/CategoriesItems0"
      }
    },
    "CategoriesItems0": {
      "type": "object",
      "properties": {
        "BroadCategoryId": {
          "type": "string"
        },
        "ImageUrl": {
          "type": "string"
        },
        "IsActive": {
          "type": "boolean"
        },
        "Name": {
          "type": "string"
        },
        "SubCategories": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CategoriesItems0SubCategoriesItems0"
          }
        }
      }
    },
    "CategoriesItems0SubCategoriesItems0": {
      "type": "object",
      "properties": {
        "ImageUrl": {
          "type": "string"
        },
        "IsActive": {
          "type": "boolean"
        },
        "Name": {
          "type": "string"
        },
        "SubCategoryId": {
          "type": "string"
        }
      }
    }
  }
}`))
}
