// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "E-Food",
    "version": "1.0.0"
  },
  "host": "e-food.com",
  "basePath": "/",
  "paths": {
    "/categories": {
      "get": {
        "tags": [
          "menu"
        ],
        "operationId": "CategoryList",
        "responses": {
          "200": {
            "description": "Get Category to show menu",
            "schema": {
              "$ref": "#/definitions/Categories"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "404": {
            "description": "Categories Not Found"
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/productListBySubCategory/{id}": {
      "get": {
        "tags": [
          "products"
        ],
        "operationId": "GetFromSubCategory",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "Subcategory Id",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Get Products based on sub category",
            "schema": {
              "$ref": "#/definitions/Products"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "404": {
            "description": "Products not found"
          },
          "500": {
            "description": "Server error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Categories": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Category"
      }
    },
    "Category": {
      "type": "object",
      "properties": {
        "bcId": {
          "type": "integer"
        },
        "bcImageUrl": {
          "type": "string"
        },
        "bcIsActive": {
          "type": "boolean"
        },
        "bcName": {
          "type": "string"
        },
        "subCategories": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SubCategory"
          }
        }
      }
    },
    "Product": {
      "type": "object",
      "properties": {
        "bcId": {
          "description": "Broad Category Id",
          "type": "integer"
        },
        "currency": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "discountPercentage": {
          "description": "Discount to be applied on Unit Price",
          "type": "number",
          "example": "1.00"
        },
        "imageUrl": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "productId": {
          "type": "number"
        },
        "scId": {
          "description": "Sub Category Id",
          "type": "integer"
        },
        "sku": {
          "type": "string"
        },
        "unitPrice": {
          "type": "number"
        }
      }
    },
    "Products": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Product"
      }
    },
    "SubCategory": {
      "type": "object",
      "properties": {
        "scId": {
          "type": "integer"
        },
        "scImageUrl": {
          "type": "string"
        },
        "scIsActive": {
          "type": "boolean"
        },
        "scName": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "E-Food",
    "version": "1.0.0"
  },
  "host": "e-food.com",
  "basePath": "/",
  "paths": {
    "/categories": {
      "get": {
        "tags": [
          "menu"
        ],
        "operationId": "CategoryList",
        "responses": {
          "200": {
            "description": "Get Category to show menu",
            "schema": {
              "$ref": "#/definitions/Categories"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "404": {
            "description": "Categories Not Found"
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/productListBySubCategory/{id}": {
      "get": {
        "tags": [
          "products"
        ],
        "operationId": "GetFromSubCategory",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "Subcategory Id",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Get Products based on sub category",
            "schema": {
              "$ref": "#/definitions/Products"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "404": {
            "description": "Products not found"
          },
          "500": {
            "description": "Server error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Categories": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Category"
      }
    },
    "Category": {
      "type": "object",
      "properties": {
        "bcId": {
          "type": "integer"
        },
        "bcImageUrl": {
          "type": "string"
        },
        "bcIsActive": {
          "type": "boolean"
        },
        "bcName": {
          "type": "string"
        },
        "subCategories": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SubCategory"
          }
        }
      }
    },
    "Product": {
      "type": "object",
      "properties": {
        "bcId": {
          "description": "Broad Category Id",
          "type": "integer"
        },
        "currency": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "discountPercentage": {
          "description": "Discount to be applied on Unit Price",
          "type": "number",
          "example": "1.00"
        },
        "imageUrl": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "productId": {
          "type": "number"
        },
        "scId": {
          "description": "Sub Category Id",
          "type": "integer"
        },
        "sku": {
          "type": "string"
        },
        "unitPrice": {
          "type": "number"
        }
      }
    },
    "Products": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Product"
      }
    },
    "SubCategory": {
      "type": "object",
      "properties": {
        "scId": {
          "type": "integer"
        },
        "scImageUrl": {
          "type": "string"
        },
        "scIsActive": {
          "type": "boolean"
        },
        "scName": {
          "type": "string"
        }
      }
    }
  }
}`))
}
