// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// AddToCartHandlerFunc turns a function with the right signature into a add to cart handler
type AddToCartHandlerFunc func(AddToCartParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn AddToCartHandlerFunc) Handle(params AddToCartParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// AddToCartHandler interface for that can handle valid add to cart params
type AddToCartHandler interface {
	Handle(AddToCartParams, interface{}) middleware.Responder
}

// NewAddToCart creates a new http.Handler for the add to cart operation
func NewAddToCart(ctx *middleware.Context, handler AddToCartHandler) *AddToCart {
	return &AddToCart{Context: ctx, Handler: handler}
}

/*AddToCart swagger:route POST /user/cart user addToCart

This API adds product to cart / guest cart

*/
type AddToCart struct {
	Context *middleware.Context
	Handler AddToCartHandler
}

func (o *AddToCart) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddToCartParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
