// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ApplyCouponHandlerFunc turns a function with the right signature into a apply coupon handler
type ApplyCouponHandlerFunc func(ApplyCouponParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ApplyCouponHandlerFunc) Handle(params ApplyCouponParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ApplyCouponHandler interface for that can handle valid apply coupon params
type ApplyCouponHandler interface {
	Handle(ApplyCouponParams, interface{}) middleware.Responder
}

// NewApplyCoupon creates a new http.Handler for the apply coupon operation
func NewApplyCoupon(ctx *middleware.Context, handler ApplyCouponHandler) *ApplyCoupon {
	return &ApplyCoupon{Context: ctx, Handler: handler}
}

/*ApplyCoupon swagger:route POST /coupon user applyCoupon

Apply coupon code

*/
type ApplyCoupon struct {
	Context *middleware.Context
	Handler ApplyCouponHandler
}

func (o *ApplyCoupon) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewApplyCouponParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
