// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CheckoutHandlerFunc turns a function with the right signature into a checkout handler
type CheckoutHandlerFunc func(CheckoutParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CheckoutHandlerFunc) Handle(params CheckoutParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CheckoutHandler interface for that can handle valid checkout params
type CheckoutHandler interface {
	Handle(CheckoutParams, interface{}) middleware.Responder
}

// NewCheckout creates a new http.Handler for the checkout operation
func NewCheckout(ctx *middleware.Context, handler CheckoutHandler) *Checkout {
	return &Checkout{Context: ctx, Handler: handler}
}

/*Checkout swagger:route GET /checkoutCart user checkout

Get Checkout Cart with offers

*/
type Checkout struct {
	Context *middleware.Context
	Handler CheckoutHandler
}

func (o *Checkout) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCheckoutParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
