// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostInitiatePaymentOKCode is the HTTP code returned for type PostInitiatePaymentOK
const PostInitiatePaymentOKCode int = 200

/*PostInitiatePaymentOK OK

swagger:response postInitiatePaymentOK
*/
type PostInitiatePaymentOK struct {
}

// NewPostInitiatePaymentOK creates PostInitiatePaymentOK with default headers values
func NewPostInitiatePaymentOK() *PostInitiatePaymentOK {

	return &PostInitiatePaymentOK{}
}

// WriteResponse to the client
func (o *PostInitiatePaymentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
