// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RemoveCouponHandlerFunc turns a function with the right signature into a remove coupon handler
type RemoveCouponHandlerFunc func(RemoveCouponParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn RemoveCouponHandlerFunc) Handle(params RemoveCouponParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// RemoveCouponHandler interface for that can handle valid remove coupon params
type RemoveCouponHandler interface {
	Handle(RemoveCouponParams, interface{}) middleware.Responder
}

// NewRemoveCoupon creates a new http.Handler for the remove coupon operation
func NewRemoveCoupon(ctx *middleware.Context, handler RemoveCouponHandler) *RemoveCoupon {
	return &RemoveCoupon{Context: ctx, Handler: handler}
}

/*RemoveCoupon swagger:route DELETE /coupon user removeCoupon

Remove coupon code

*/
type RemoveCoupon struct {
	Context *middleware.Context
	Handler RemoveCouponHandler
}

func (o *RemoveCoupon) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRemoveCouponParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
