// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"e-food/models"
)

// RemoveCouponOKCode is the HTTP code returned for type RemoveCouponOK
const RemoveCouponOKCode int = 200

/*RemoveCouponOK response when coupon is consumed

swagger:response removeCouponOK
*/
type RemoveCouponOK struct {

	/*
	  In: Body
	*/
	Payload *models.SuccessResponse `json:"body,omitempty"`
}

// NewRemoveCouponOK creates RemoveCouponOK with default headers values
func NewRemoveCouponOK() *RemoveCouponOK {

	return &RemoveCouponOK{}
}

// WithPayload adds the payload to the remove coupon o k response
func (o *RemoveCouponOK) WithPayload(payload *models.SuccessResponse) *RemoveCouponOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the remove coupon o k response
func (o *RemoveCouponOK) SetPayload(payload *models.SuccessResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RemoveCouponOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RemoveCouponBadRequestCode is the HTTP code returned for type RemoveCouponBadRequest
const RemoveCouponBadRequestCode int = 400

/*RemoveCouponBadRequest Bad Request

swagger:response removeCouponBadRequest
*/
type RemoveCouponBadRequest struct {
}

// NewRemoveCouponBadRequest creates RemoveCouponBadRequest with default headers values
func NewRemoveCouponBadRequest() *RemoveCouponBadRequest {

	return &RemoveCouponBadRequest{}
}

// WriteResponse to the client
func (o *RemoveCouponBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// RemoveCouponNotFoundCode is the HTTP code returned for type RemoveCouponNotFound
const RemoveCouponNotFoundCode int = 404

/*RemoveCouponNotFound Item to be added Not Found

swagger:response removeCouponNotFound
*/
type RemoveCouponNotFound struct {
}

// NewRemoveCouponNotFound creates RemoveCouponNotFound with default headers values
func NewRemoveCouponNotFound() *RemoveCouponNotFound {

	return &RemoveCouponNotFound{}
}

// WriteResponse to the client
func (o *RemoveCouponNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// RemoveCouponInternalServerErrorCode is the HTTP code returned for type RemoveCouponInternalServerError
const RemoveCouponInternalServerErrorCode int = 500

/*RemoveCouponInternalServerError Server error

swagger:response removeCouponInternalServerError
*/
type RemoveCouponInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewRemoveCouponInternalServerError creates RemoveCouponInternalServerError with default headers values
func NewRemoveCouponInternalServerError() *RemoveCouponInternalServerError {

	return &RemoveCouponInternalServerError{}
}

// WithPayload adds the payload to the remove coupon internal server error response
func (o *RemoveCouponInternalServerError) WithPayload(payload string) *RemoveCouponInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the remove coupon internal server error response
func (o *RemoveCouponInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RemoveCouponInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
