// Code generated by go-swagger; DO NOT EDIT.

package guest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// AddSessionHandlerFunc turns a function with the right signature into a add session handler
type AddSessionHandlerFunc func(AddSessionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddSessionHandlerFunc) Handle(params AddSessionParams) middleware.Responder {
	return fn(params)
}

// AddSessionHandler interface for that can handle valid add session params
type AddSessionHandler interface {
	Handle(AddSessionParams) middleware.Responder
}

// NewAddSession creates a new http.Handler for the add session operation
func NewAddSession(ctx *middleware.Context, handler AddSessionHandler) *AddSession {
	return &AddSession{Context: ctx, Handler: handler}
}

/*AddSession swagger:route POST /sessionInfo guest addSession

Adds Cookie ID for guests

*/
type AddSession struct {
	Context *middleware.Context
	Handler AddSessionHandler
}

func (o *AddSession) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddSessionParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
