// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LoginSuccess login success
//
// swagger:model LoginSuccess
type LoginSuccess struct {

	// success
	Success bool `json:"success,omitempty"`

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this login success
func (m *LoginSuccess) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LoginSuccess) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LoginSuccess) UnmarshalBinary(b []byte) error {
	var res LoginSuccess
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
