// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"e-food/api/models"
)

// AddToCartOKCode is the HTTP code returned for type AddToCartOK
const AddToCartOKCode int = 200

/*AddToCartOK Success response when item is added successfully

swagger:response addToCartOK
*/
type AddToCartOK struct {

	/*
	  In: Body
	*/
	Payload *models.CartSuccessResponse `json:"body,omitempty"`
}

// NewAddToCartOK creates AddToCartOK with default headers values
func NewAddToCartOK() *AddToCartOK {

	return &AddToCartOK{}
}

// WithPayload adds the payload to the add to cart o k response
func (o *AddToCartOK) WithPayload(payload *models.CartSuccessResponse) *AddToCartOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add to cart o k response
func (o *AddToCartOK) SetPayload(payload *models.CartSuccessResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddToCartOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddToCartBadRequestCode is the HTTP code returned for type AddToCartBadRequest
const AddToCartBadRequestCode int = 400

/*AddToCartBadRequest Bad Request

swagger:response addToCartBadRequest
*/
type AddToCartBadRequest struct {
}

// NewAddToCartBadRequest creates AddToCartBadRequest with default headers values
func NewAddToCartBadRequest() *AddToCartBadRequest {

	return &AddToCartBadRequest{}
}

// WriteResponse to the client
func (o *AddToCartBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// AddToCartNotFoundCode is the HTTP code returned for type AddToCartNotFound
const AddToCartNotFoundCode int = 404

/*AddToCartNotFound Item to be added Not Found

swagger:response addToCartNotFound
*/
type AddToCartNotFound struct {
}

// NewAddToCartNotFound creates AddToCartNotFound with default headers values
func NewAddToCartNotFound() *AddToCartNotFound {

	return &AddToCartNotFound{}
}

// WriteResponse to the client
func (o *AddToCartNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// AddToCartInternalServerErrorCode is the HTTP code returned for type AddToCartInternalServerError
const AddToCartInternalServerErrorCode int = 500

/*AddToCartInternalServerError Server error

swagger:response addToCartInternalServerError
*/
type AddToCartInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewAddToCartInternalServerError creates AddToCartInternalServerError with default headers values
func NewAddToCartInternalServerError() *AddToCartInternalServerError {

	return &AddToCartInternalServerError{}
}

// WithPayload adds the payload to the add to cart internal server error response
func (o *AddToCartInternalServerError) WithPayload(payload string) *AddToCartInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add to cart internal server error response
func (o *AddToCartInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddToCartInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
