// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"e-food/api/models"
)

// ApplyCouponOKCode is the HTTP code returned for type ApplyCouponOK
const ApplyCouponOKCode int = 200

/*ApplyCouponOK response when coupon is consumed

swagger:response applyCouponOK
*/
type ApplyCouponOK struct {

	/*
	  In: Body
	*/
	Payload *models.SuccessResponse `json:"body,omitempty"`
}

// NewApplyCouponOK creates ApplyCouponOK with default headers values
func NewApplyCouponOK() *ApplyCouponOK {

	return &ApplyCouponOK{}
}

// WithPayload adds the payload to the apply coupon o k response
func (o *ApplyCouponOK) WithPayload(payload *models.SuccessResponse) *ApplyCouponOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the apply coupon o k response
func (o *ApplyCouponOK) SetPayload(payload *models.SuccessResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ApplyCouponOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ApplyCouponBadRequestCode is the HTTP code returned for type ApplyCouponBadRequest
const ApplyCouponBadRequestCode int = 400

/*ApplyCouponBadRequest Bad Request

swagger:response applyCouponBadRequest
*/
type ApplyCouponBadRequest struct {
}

// NewApplyCouponBadRequest creates ApplyCouponBadRequest with default headers values
func NewApplyCouponBadRequest() *ApplyCouponBadRequest {

	return &ApplyCouponBadRequest{}
}

// WriteResponse to the client
func (o *ApplyCouponBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// ApplyCouponNotFoundCode is the HTTP code returned for type ApplyCouponNotFound
const ApplyCouponNotFoundCode int = 404

/*ApplyCouponNotFound Item to be added Not Found

swagger:response applyCouponNotFound
*/
type ApplyCouponNotFound struct {
}

// NewApplyCouponNotFound creates ApplyCouponNotFound with default headers values
func NewApplyCouponNotFound() *ApplyCouponNotFound {

	return &ApplyCouponNotFound{}
}

// WriteResponse to the client
func (o *ApplyCouponNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// ApplyCouponInternalServerErrorCode is the HTTP code returned for type ApplyCouponInternalServerError
const ApplyCouponInternalServerErrorCode int = 500

/*ApplyCouponInternalServerError Server error

swagger:response applyCouponInternalServerError
*/
type ApplyCouponInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewApplyCouponInternalServerError creates ApplyCouponInternalServerError with default headers values
func NewApplyCouponInternalServerError() *ApplyCouponInternalServerError {

	return &ApplyCouponInternalServerError{}
}

// WithPayload adds the payload to the apply coupon internal server error response
func (o *ApplyCouponInternalServerError) WithPayload(payload string) *ApplyCouponInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the apply coupon internal server error response
func (o *ApplyCouponInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ApplyCouponInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
