// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"e-food/api/models"
)

// CouponOKCode is the HTTP code returned for type CouponOK
const CouponOKCode int = 200

/*CouponOK response when coupon is consumed

swagger:response couponOK
*/
type CouponOK struct {

	/*
	  In: Body
	*/
	Payload *models.SuccessResponse `json:"body,omitempty"`
}

// NewCouponOK creates CouponOK with default headers values
func NewCouponOK() *CouponOK {

	return &CouponOK{}
}

// WithPayload adds the payload to the coupon o k response
func (o *CouponOK) WithPayload(payload *models.SuccessResponse) *CouponOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the coupon o k response
func (o *CouponOK) SetPayload(payload *models.SuccessResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CouponOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CouponBadRequestCode is the HTTP code returned for type CouponBadRequest
const CouponBadRequestCode int = 400

/*CouponBadRequest Bad Request

swagger:response couponBadRequest
*/
type CouponBadRequest struct {
}

// NewCouponBadRequest creates CouponBadRequest with default headers values
func NewCouponBadRequest() *CouponBadRequest {

	return &CouponBadRequest{}
}

// WriteResponse to the client
func (o *CouponBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// CouponNotFoundCode is the HTTP code returned for type CouponNotFound
const CouponNotFoundCode int = 404

/*CouponNotFound Item to be added Not Found

swagger:response couponNotFound
*/
type CouponNotFound struct {
}

// NewCouponNotFound creates CouponNotFound with default headers values
func NewCouponNotFound() *CouponNotFound {

	return &CouponNotFound{}
}

// WriteResponse to the client
func (o *CouponNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// CouponInternalServerErrorCode is the HTTP code returned for type CouponInternalServerError
const CouponInternalServerErrorCode int = 500

/*CouponInternalServerError Server error

swagger:response couponInternalServerError
*/
type CouponInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewCouponInternalServerError creates CouponInternalServerError with default headers values
func NewCouponInternalServerError() *CouponInternalServerError {

	return &CouponInternalServerError{}
}

// WithPayload adds the payload to the coupon internal server error response
func (o *CouponInternalServerError) WithPayload(payload string) *CouponInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the coupon internal server error response
func (o *CouponInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CouponInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
