// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CouponHandlerFunc turns a function with the right signature into a coupon handler
type CouponHandlerFunc func(CouponParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CouponHandlerFunc) Handle(params CouponParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CouponHandler interface for that can handle valid coupon params
type CouponHandler interface {
	Handle(CouponParams, interface{}) middleware.Responder
}

// NewCoupon creates a new http.Handler for the coupon operation
func NewCoupon(ctx *middleware.Context, handler CouponHandler) *Coupon {
	return &Coupon{Context: ctx, Handler: handler}
}

/*Coupon swagger:route POST /applyCoupon user coupon

Apply coupon code

*/
type Coupon struct {
	Context *middleware.Context
	Handler CouponHandler
}

func (o *Coupon) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCouponParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
