// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// InitPayOKCode is the HTTP code returned for type InitPayOK
const InitPayOKCode int = 200

/*InitPayOK OK

swagger:response initPayOK
*/
type InitPayOK struct {

	/*
	  In: Body
	*/
	Payload *InitPayOKBody `json:"body,omitempty"`
}

// NewInitPayOK creates InitPayOK with default headers values
func NewInitPayOK() *InitPayOK {

	return &InitPayOK{}
}

// WithPayload adds the payload to the init pay o k response
func (o *InitPayOK) WithPayload(payload *InitPayOKBody) *InitPayOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the init pay o k response
func (o *InitPayOK) SetPayload(payload *InitPayOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *InitPayOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// InitPayBadRequestCode is the HTTP code returned for type InitPayBadRequest
const InitPayBadRequestCode int = 400

/*InitPayBadRequest Bad Request

swagger:response initPayBadRequest
*/
type InitPayBadRequest struct {
}

// NewInitPayBadRequest creates InitPayBadRequest with default headers values
func NewInitPayBadRequest() *InitPayBadRequest {

	return &InitPayBadRequest{}
}

// WriteResponse to the client
func (o *InitPayBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// InitPayNotFoundCode is the HTTP code returned for type InitPayNotFound
const InitPayNotFoundCode int = 404

/*InitPayNotFound Item to be added Not Found

swagger:response initPayNotFound
*/
type InitPayNotFound struct {
}

// NewInitPayNotFound creates InitPayNotFound with default headers values
func NewInitPayNotFound() *InitPayNotFound {

	return &InitPayNotFound{}
}

// WriteResponse to the client
func (o *InitPayNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// InitPayInternalServerErrorCode is the HTTP code returned for type InitPayInternalServerError
const InitPayInternalServerErrorCode int = 500

/*InitPayInternalServerError Server error

swagger:response initPayInternalServerError
*/
type InitPayInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewInitPayInternalServerError creates InitPayInternalServerError with default headers values
func NewInitPayInternalServerError() *InitPayInternalServerError {

	return &InitPayInternalServerError{}
}

// WithPayload adds the payload to the init pay internal server error response
func (o *InitPayInternalServerError) WithPayload(payload string) *InitPayInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the init pay internal server error response
func (o *InitPayInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *InitPayInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
