// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RemoveFromCartHandlerFunc turns a function with the right signature into a remove from cart handler
type RemoveFromCartHandlerFunc func(RemoveFromCartParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn RemoveFromCartHandlerFunc) Handle(params RemoveFromCartParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// RemoveFromCartHandler interface for that can handle valid remove from cart params
type RemoveFromCartHandler interface {
	Handle(RemoveFromCartParams, interface{}) middleware.Responder
}

// NewRemoveFromCart creates a new http.Handler for the remove from cart operation
func NewRemoveFromCart(ctx *middleware.Context, handler RemoveFromCartHandler) *RemoveFromCart {
	return &RemoveFromCart{Context: ctx, Handler: handler}
}

/*RemoveFromCart swagger:route DELETE /user/cart user removeFromCart

Remove item from cart

*/
type RemoveFromCart struct {
	Context *middleware.Context
	Handler RemoveFromCartHandler
}

func (o *RemoveFromCart) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRemoveFromCartParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
