swagger: '2.0'
info:
  version: '1.0.0'
  title: E-Food
schemes: [http]
host: e-food.com
basePath: /
consumes: [application/json]
produces: [application/json]
paths:
  /categories:
    get:
      tags: [menu]
      operationId: CategoryList
      responses:
        200:
          description: 'Get Category to show menu'
          schema:
            $ref: '#/definitions/Categories'
        400:
          description: Bad Request
        404:
          description: Categories Not Found
        500:
          schema:
            type: string
          description: Server Error
  /productListBySubCategory/{id}:
    get:
      tags: [products]
      operationId: GetFromSubCategory
      parameters:
        - name: "id"
          in : "path"
          type: integer
          format: int64
          required: true
          description: Subcategory Id
      responses:
        200:
          description: 'Get Products based on sub category'
          schema:
            $ref: '#/definitions/Products'
        400:
          description : Bad Request
        404:
          description: Products not found
        500:
          schema:
            type: string
          description: Server error
definitions:
  Categories:
    type: array
    items:
      $ref: '#/definitions/Category'
  Category:
    type: object
    properties:
      bcId:
        type: integer
      bcName:
        type: string
      bcImageUrl:
        type: string
      bcIsActive:
        type: boolean
      subCategories:
        type: array
        items:
          $ref: '#/definitions/SubCategory'
  SubCategory:
    type: object
    properties:
      scId:
        type: integer
      scName:
        type: string
      scImageUrl:
        type: string
      scIsActive:
        type: boolean
  Products:
    type: array
    items:
      $ref: '#/definitions/Product'
  Product:
    type: object
    properties:
      productId:
        type: number
      name:
        type: string
      sku:
        type: string
      description:
        type: string
      bcId:
        type: integer
        description: Broad Category Id
      currency:
        type: string
      imageUrl:
        type: string
      discountPercentage:
        type: number
        example: "1.00"
        description: Discount to be applied on Unit Price
      unitPrice:
        type: number
      scId:
        type: integer
        description: Sub Category Id



