swagger: '2.0'
info:
  version: '1.0.0'
  title: E-Food
schemes: [http]
host: e-food.com
basePath: /
consumes: [application/json]
produces: [application/json]
paths:
  /categories:
    get:
      tags: [menu]
      operationId: CategoryList
      responses:
        200:
          description: 'Get Category to show menu'
          schema:
            $ref: '#/definitions/Categories'
        400:
          description: Bad Request
        404:
          description: Categories Not Found

definitions:
  Categories:
    type: array
    items:
      $ref: '#/definitions/Category'
  Category:
    type: object
    properties:
      bcId:
        type: string
      bcName:
        type: string
      bcImageUrl:
        type: string
      bcIsActive:
        type: boolean
      subCategories:
        type: array
        items:
          $ref: '#/definitions/SubCategory'
  SubCategory:
    type: object
    properties:
      scId:
        type: string
      scName:
        type: string
      scImageUrl:
        type: string
      scIsActive:
        type: boolean


