// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BillableCart billable cart
//
// swagger:model BillableCart
type BillableCart struct {

	// coupon Id
	CouponID string `json:"couponId,omitempty"`

	// currency
	Currency string `json:"currency,omitempty"`

	// items
	Items []*BillingItem `json:"items"`

	// offer items
	OfferItems []*OfferItem `json:"offerItems"`

	// total price
	TotalPrice float64 `json:"totalPrice,omitempty"`

	// total saving
	TotalSaving float64 `json:"totalSaving,omitempty"`
}

// Validate validates this billable cart
func (m *BillableCart) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateItems(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOfferItems(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BillableCart) validateItems(formats strfmt.Registry) error {

	if swag.IsZero(m.Items) { // not required
		return nil
	}

	for i := 0; i < len(m.Items); i++ {
		if swag.IsZero(m.Items[i]) { // not required
			continue
		}

		if m.Items[i] != nil {
			if err := m.Items[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("items" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *BillableCart) validateOfferItems(formats strfmt.Registry) error {

	if swag.IsZero(m.OfferItems) { // not required
		return nil
	}

	for i := 0; i < len(m.OfferItems); i++ {
		if swag.IsZero(m.OfferItems[i]) { // not required
			continue
		}

		if m.OfferItems[i] != nil {
			if err := m.OfferItems[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("offerItems" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *BillableCart) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BillableCart) UnmarshalBinary(b []byte) error {
	var res BillableCart
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
