// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CartSuccessResponse cart success response
//
// swagger:model CartSuccessResponse
type CartSuccessResponse struct {

	// success
	Success bool `json:"success,omitempty"`

	// total item count
	TotalItemCount float64 `json:"totalItemCount,omitempty"`
}

// Validate validates this cart success response
func (m *CartSuccessResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CartSuccessResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CartSuccessResponse) UnmarshalBinary(b []byte) error {
	var res CartSuccessResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
